### ISSUE TITLE
合作

### ISSUE THREAD

**Issue by dalinzhang** [brandonlist/midecode616#1]
你好，我对你的项目很感兴趣，想进一步讨论合作的可能。如果方便，能否留个联系方式（邮箱等）进一步联系，十分感谢！

**Comment by brandonlist** [comment]
非常感谢！我的邮箱是haohao9806@163.com

**Comment by brandonlist** [comment]
非常感谢大神！我在今年毕业设计期间拜读过大神的论文，您提出的关于EEG分类中R-CNN设计的观点十分深刻！
我的邮箱是haohao9806@163.com，学校的邮箱是1120160953@bit.edu.cn，十分期待与大神的合作！



















在 2020-07-09 12:59:48，"Dalin Zhang" <notifications@github.com> 写道：

你好，我对你的项目很感兴趣，想进一步讨论合作的可能。如果方便，能否留个联系方式（邮箱等）进一步联系，十分感谢！
